(use rfc.xmpp)

(define c (xmpp-connect "localhost"))
(xmpp-auth c "yourname" "yourpass")
(xmpp-bind c "Home")
(xmpp-session c)
(xmpp-presence c)
(xmpp-message (c :to "world@localhost")
              "Hello World.")
(xmpp-get-roster c)
(xmpp-receive-stanza c)
(xmpp-receive-stanza c)
(xmpp-receive-stanza c)
(xmpp-disconnect c)
